name: Send notifications

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8,16 * * *"

jobs:
  npm-script:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - run: deno task notify

      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add --all
          git diff-index --quiet HEAD || git commit -m "GitHub Action save state" && git push

