name: Send notifications

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8,16 * * *"

jobs:
  npm-script:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - run: deno task notify
        env:
          BOT_KEY:  ${{ secrets.BOT_KEY }}
          CHAT_ID:  ${{ secrets.CHAT_ID }}
          MAL_CLIENT_ID:  ${{ secrets.MAL_CLIENT_ID }}
          MAL_USER_NAME:  ${{ secrets.MAL_USER_NAME }}

      - run: |
          git diff --exit-code merged-state.json || (
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add merged-state.json
          git commit -m 'Update state ny GitHub Action'
          git push
          )

